server:
  port: 8081

spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: My$QLr00t
    url: jdbc:mysql://localhost:5306/drycleaning

  jpa:
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

#spring:
#  datasource:
#    url: jdbc:h2:file:./spring_test
#    username: sa
#    password: password
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#  sql:
#    init:
#      mode: always
#  freemarker:
#    suffix: .ftlh
#    settings:
#      recognize_standard_file_extensions: true
#springdoc:
#  swagger-ui:
#    disable-swagger-default-url: true

